
name: 'linkedin_source'
version: '1.0.0'
config-version: 2

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
    linkedin_source:
        materialized: view

vars:
    linkedin_source:
        linkedin__use_local_currency: true
        account_history: "{{ source('linkedin','account_history') }}"
        ad_analytics_by_creative: "{{ source('linkedin','ad_analytics_by_creative') }}"
        campaign_group_history: "{{ source('linkedin','campaign_group_history') }}"
        campaign_history: "{{ source('linkedin','campaign_history') }}"
        creative_history: "{{ source('linkedin','creative_history') }}"