
name: 'linkedin_source'
version: '1.0.0'
config-version: 2

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

vars:
    linkedin__use_local_currency: true

models:
    linkedin_source:
        materialized: view
