analysis-paths:
- analysis
config-version: 2
data-paths:
- data
macro-paths:
- macros
models:
  linkedin_source:
    materialized: view
name: linkedin_source
require-dbt-version:
- '>=0.18.0'
- <0.19.0
snapshot-paths:
- snapshots
source-paths:
- models
test-paths:
- tests
vars:
  linkedin__use_local_currency: true
version: 1.0.0
