name: 'linkedin_source'
version: '0.3.0'
config-version: 2
require-dbt-version: [">=0.20.0"]
models:
  linkedin_source:
    +materialized: view
    +schema: stg_linkedin
vars:
  linkedin_source:
    linkedin__use_local_currency: true
    account_history: "{{ source('linkedin','account_history') }}"
    ad_analytics_by_creative: "{{ source('linkedin','ad_analytics_by_creative') }}"
    campaign_group_history: "{{ source('linkedin','campaign_group_history') }}"
    campaign_history: "{{ source('linkedin','campaign_history') }}"
    creative_history: "{{ source('linkedin','creative_history') }}"
  linkedin__passthrough_metrics: []
