name: 'linkedin_source_integration_tests'
version: '0.5.0'
profile: 'integration_tests'
config-version: 2

vars:
  linkedin_source:
    linkedin_ads_account_history_identifier: "linkedin_account_history_data"
    linkedin_ads_ad_analytics_by_creative_identifier: "linkedin_ad_analytics_by_creative_data"
    linkedin_ads_campaign_group_history_identifier: "linkedin_campaign_group_history_data"
    linkedin_ads_campaign_history_identifier: "linkedin_campaign_history_data"
    linkedin_ads_creative_history_identifier: "linkedin_creative_history_data"
    linkedin_ads_ad_analytics_by_campaign_identifier: "linkedin_ad_analytics_by_campaign_data"

    linkedin_ads_schema: linkedin_source_integration_tests

seeds:
  linkedin_source_integration_tests:
    linkedin_creative_history_data:
      +column_types:
        created_time: timestamp
        last_modified_time: timestamp
        click_uri: "{{ 'string' if target.type in ('bigquery', 'spark') else 'varchar' }}"
    linkedin_ad_analytics_by_creative_data:
      +column_types:
        day: timestamp
    linkedin_account_history_data:
      +column_types:
        created_time: timestamp
        last_modified_time: timestamp
    linkedin_campaign_group_history_data:
      +column_types:
        created_time: timestamp
        last_modified_time: timestamp
    linkedin_campaign_history_data:
      +column_types:
        created_time: timestamp
        last_modified_time: timestamp
        
dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']
