name: 'linkedin_source_integration_tests'
version: '1.0.0'
profile: 'integration_tests'
config-version: 2

vars:
  linkedin_source:
        account_history: "{{ ref('linkedin_account_history_data') }}"
        ad_analytics_by_creative: "{{ ref('linkedin_ad_analytics_by_creative_data') }}"
        campaign_group_history: "{{ ref('linkedin_campaign_group_history_data') }}"
        campaign_history: "{{ ref('linkedin_campaign_history_data') }}"
        creative_history: "{{ ref('linkedin_creative_history_data') }}"

seeds:
  linkedin_source_integration_tests:
    linkedin_creative_history_data:
      +column_types:
        created_time: timestamp
        last_modified_time: timestamp
        click_uri: "{{ 'string' if target.type == 'bigquery' else 'varchar' }}"
    linkedin_ad_analytics_by_creative_data:
      +column_types:
        day: timestamp
    linkedin_account_history_data:
      +column_types:
        created_time: timestamp
        last_modified_time: timestamp
    linkedin_campaign_group_history_data:
      +column_types:
        created_time: timestamp
        last_modified_time: timestamp
    linkedin_campaign_history_data:
      +column_types:
        created_time: timestamp
        last_modified_time: timestamp
    linkedin_creative_history_data:
      +column_types:
        created_time: timestamp
        last_modified_time: timestamp